[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/cheerain-backend-1.0.0.jar'
